[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.20'  # Specify Solidity version
optimizer = true
optimizer_runs = 200
dotenv = ".env"
etherscan_api_key = "ZSDZ4J3JQGAANTTAGJAEAI1MNVHC6BZGXJ"

[rpc_endpoints]
scroll_sepolia = "https://sepolia-rpc.scroll.io"  # Replace with actual RPC URL if needed